// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "2af4a365-b804-4f5c-8886-11645ce51f3d");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1665985360);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1665985480);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1666002880);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1665985120);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1665985000);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1665985240);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1665985720);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1665985600);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 215040);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1665984849);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0d61578e-a519-4b6e-83c4-104bdb5053ec}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1665936000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1666004711479");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1666006493479");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1665984855014");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1666006455014");
user_pref("browser.search.region", "TW");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1665984851");
user_pref("browser.slowStartup.averageTime", 1573);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190215002024");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1665984853186");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "ef81559a4efd4ee89167076d042e81f2");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1665985361);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a54ad78b-4939-4028-bada-cfd332068a0b\",\"screenshots@mozilla.org\":\"f94c86a1-20ac-4d9e-8565-1c49f8e23675\",\"webcompat-reporter@mozilla.org\":\"0279c137-c32c-43de-b00a-de059e8b49d3\",\"webcompat@mozilla.org\":\"d671199e-29b3-48b9-aad0-875ae0a19f9a\",\"baidu-code-update@mozillaonline.com\":\"2fa0911c-d4b7-430c-b6f8-e6b5b6303eaf\",\"fxmonitor@mozilla.org\":\"f81b4b3d-76a3-4ed7-98ca-3719718bae7a\"}");
user_pref("idle.lastDailyNotification", 1665985577);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1665985108);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190215002024");
user_pref("media.gmp-manager.lastCheck", 1665985107);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1665985577);
user_pref("places.history.expiration.transient_current_max_pages", 53345);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "7deabe0a-2cd4-4a88-9c84-e59336bda6a5");
user_pref("security.sandbox.plugin.tempDirSuffix", "89dcaede-3e29-453e-8ccc-7578c8ab9f10");
user_pref("services.blocklist.addons.checked", 1665985107);
user_pref("services.blocklist.gfx.checked", 1665985107);
user_pref("services.blocklist.onecrl.checked", 1665985107);
user_pref("services.blocklist.plugins.checked", 1665985107);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1665989833208\"");
user_pref("services.settings.last_update_seconds", 1665990213);
user_pref("services.settings.main.language-dictionaries.last_check", 1665985107);
user_pref("services.settings.main.sites-classification.last_check", 1665985107);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1665985577);
user_pref("toolkit.startup.last_success", 1665984849);
user_pref("toolkit.telemetry.cachedClientID", "ad6bacb2-d488-4419-83f4-6f20165cc647");
user_pref("toolkit.telemetry.previousBuildID", "20190215002024");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
